# Generated by Django 5.0.9 on 2024-09-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.playlist'),
        ),
    ]
