# Generated by Django 5.0.9 on 2024-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='songs_cover/'),
        ),
    ]
