# Generated by Django 5.0.9 on 2024-11-30 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_like_songlike_alter_songlike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='songlike',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to='music.song'),
        ),
        migrations.AlterField(
            model_name='songlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
