# Generated by Django 5.0.9 on 2024-12-25 17:35

import music.custom_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_options_alter_playlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, storage=music.custom_storage.MediaStorage(), upload_to='album_cover/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_cover',
            field=models.ImageField(blank=True, storage=music.custom_storage.MediaStorage(), upload_to='playlist_cover/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, storage=music.custom_storage.MediaStorage(), upload_to='', verbose_name='songs_cover/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.FileField(storage=music.custom_storage.MediaStorage(), upload_to='songs/'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'album')},
        ),
    ]
