# Generated by Django 5.0.9 on 2024-12-26 04:41

import django.db.models.deletion
import music.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_album_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='music.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, storage=music.custom_storage.MediaStorage(), upload_to='songs_cover/'),
        ),
    ]
